variables:
  MAJOR_VERSION: "1"
  MINOR_VERSION: "5"
  MAINTENANCE_VERSION: '2'
  DOCKER_PUBLISH_ENABLED: 'false'

include:
  - project: 'vivarium/th2/pipelines'
    ref: master
    file: '/.gitlab-ci-java.yml'
